kind = "web"
previewPath = "/"
title = "Plenfow"
version = "1.0.0"
id = "artifacts/plenfow"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24829

[services.development]
run = "pnpm --filter @workspace/plenfow run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/plenfow", "run", "build" ]
publicDir = "artifacts/plenfow/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24829"
BASE_PATH = "/"
